apiVersion: v1 
kind: PersistentVolume
metadata: 
  name: gulzat-safari-pv
spec: 
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/Volume/Data


  